---
all:
  vars:
    ansible_user: janoger
    ansible_password: hackathon
  hosts:
    duck1:
      ansible_connection: local
      ansible_host: localhost
  children:
    server:
      vars:
        ansible_ssh_port: 22
        ansible_ssh_user: janoger
        ansible_ssh_pass: hackathon
        ansible_sudo_pass: hackathon
      hosts:
        duck2:
          ansible_host: 192.168.10.8
        goose:
          ansible_host: 192.168.10.9
          ansible_connection: network_cli
          ansible_network_os: ios
